### ISSUE TITLE
raspicamview.py error on raspi 4

### ISSUE THREAD

**Issue by hymi54** [Video-Streaming-Pipeline/Video-Streaming-Pipeline#23]
Traceback (most recent call last):
  File "raspicamview.py", line 48, in <module>
    s=Process(target=sending,args=(temp_time))
  File "/usr/lib/python3.7/multiprocessing/process.py", line 82, in __init__
    self._args = tuple(args)
TypeError: 'Synchronized' object is not iterable

**Comment by BEOKS** [comment]
https://github.com/Video-Streaming-Pipeline/Video-Streaming-Pipeline/blob/3b06cff76397d89d95fc189753adb736978ef823/raspi/raspicamview.py#L48
https://github.com/Video-Streaming-Pipeline/Video-Streaming-Pipeline/blob/3b06cff76397d89d95fc189753adb736978ef823/raspi/raspicamview.py#L49

위 코드 두 개에서 temp_time 뒤에 , 붙여봐

**Comment by hymi54** [comment]
> Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "raspicamview.py", line 22, in sending
    temp_time.value=time()
TypeError: 'module' object is not callable

New error

**Comment by BEOKS** [comment]
https://github.com/Video-Streaming-Pipeline/Video-Streaming-Pipeline/blob/3b06cff76397d89d95fc189753adb736978ef823/raspi/raspicamview.py#L8
라인 삭제 ㄱ
